// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAorwIBdOpzUtGAjnGkAdx4PPmVsOe6Mns',
    appId: '1:796760578511:web:318e54bd0ea09fafe89aba',
    messagingSenderId: '796760578511',
    projectId: 'ecommunity-3eddc',
    authDomain: 'ecommunity-3eddc.firebaseapp.com',
    storageBucket: 'ecommunity-3eddc.firebasestorage.app',
    measurementId: 'G-1Q8E0ZQ6JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOevcRzlUp8Nsxwsl-1Jr6R-4LTpK9xz0',
    appId: '1:796760578511:android:ce5ee33f919f04e3e89aba',
    messagingSenderId: '796760578511',
    projectId: 'ecommunity-3eddc',
    storageBucket: 'ecommunity-3eddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAudqQQoSUJbXq8_VYiLQjnoob-DxJJhpg',
    appId: '1:796760578511:ios:8b78c3ce843a436be89aba',
    messagingSenderId: '796760578511',
    projectId: 'ecommunity-3eddc',
    storageBucket: 'ecommunity-3eddc.firebasestorage.app',
    iosBundleId: 'com.example.ecommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAudqQQoSUJbXq8_VYiLQjnoob-DxJJhpg',
    appId: '1:796760578511:ios:8b78c3ce843a436be89aba',
    messagingSenderId: '796760578511',
    projectId: 'ecommunity-3eddc',
    storageBucket: 'ecommunity-3eddc.firebasestorage.app',
    iosBundleId: 'com.example.ecommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAorwIBdOpzUtGAjnGkAdx4PPmVsOe6Mns',
    appId: '1:796760578511:web:1c16366135f732a1e89aba',
    messagingSenderId: '796760578511',
    projectId: 'ecommunity-3eddc',
    authDomain: 'ecommunity-3eddc.firebaseapp.com',
    storageBucket: 'ecommunity-3eddc.firebasestorage.app',
    measurementId: 'G-KKD2MX1BYY',
  );
}
